### ISSUE TITLE
What is the base URL of this api?

### ISSUE THREAD

**Issue by fourjr** [axaygadekar/brawlstars-api#1]

**Comment by Epsilon10** [comment]
Yeah I was wondering that as well

**Comment by akenoyuki** [comment]
Any news regarding this?

**Comment by akenoyuki** [comment]
Same here

**Comment by kranemax** [comment]
Hey guys, check out my repository at https://www.github.com/brawlstarsAPI/api

**Comment by axaygadekar** [comment]
Readme updated now check.
